pirogramming/TripTailor

.gitignore
=> [fix] gitignore .csv, .index 추가

static/css/main.css, static/css/place_detail.css, static/css/search.css, templates/places/main.html, templates/places/place_detail.html, templates/search.html
-   [x] 리팩토링 (Refactor)
-   작업 내용
-   [ ] Task1
=> [style] main.html, search.html, place_detail.html 초안

apps/routes/urls.py, apps/routes/views.py, static/js/edit_route.js, static/js/route_detail.js, static/js/script.js, templates/places/main.html, templates/routes/create_route.html, templates/routes/detail.html, templates/routes/edit_route.html, templates/routes/route_list.html, templates/users/mypage.html
-   [x] 기능 추가 (Feature)
-   작업 내용
-   [ ] Task1
=> fix:공개/비공개 버그 수정 & feat:루트 생성 페이지

static/css/style.css
-   [x] 리뷰 반영 (Review Update)
-   작업 내용
-   [ ] Task1
=> [style] nav에 position적용

templates/base.html, templates/routes/edit_route.html
=> fix:마이페이지 url수정 & 루트 수정 페이지

templates/base.html
-   [x] 기능 추가 (Feature)
-   작업 내용
-   [ ] Task1
=> feat: 햄버거바에 루트 생성 링크 연결

templates/routes/edit_route.html
=> fix: 루트 수정 후 저장 버그 해결

apps/places/views.py, static/css/main.css, static/css/style.css, static/js/like.js, static/js/script.js, templates/places/main.html
=> [style] base, main final

static/css/main.css, static/css/place_route.css, static/css/style.css, static/css/whole_route.css, static/js/tabbar.js, templates/places/main.html, templates/places/place_detail.html, templates/routes/place_routes.html, templates/routes/route_list.html
-   [x] 기능 추가 (Feature)
-   [x] 리뷰 반영 (Review Update)
-   작업 내용
-   [ ] Task1
=> [style, fix] CSS및 HTML수정

static/css/users/mypage.css, static/css/users/reviews.css, static/css/users/routes.css, templates/users/mypage.html, templates/users/reviews.html, templates/users/routes.html
-   [x] 리팩토링 (Refactor)
-   작업 내용
-   [ ] Task1
=> design: 마이페이지 초안

static/css/users/mypage.css, templates/users/mypage.html
=> [style] mypage

apps/routes/urls.py, apps/routes/views.py, templates/routes/edit_route.html, templates/routes/route_list.html, templates/users/routes.html
-   [x] 기능 제거 (Remove)
-   작업 내용
-   [ ] Task1
=> fix: 루트 수정 후 리다이렉션 수정

static/css/main.css, static/css/search.css, static/css/style.css, templates/places/main.html, templates/search.html
-   [x] 리뷰 반영 (Review Update)
-   작업 내용
-   [ ] Task1
=> [style] fianl..?

static/css/place_route.css, static/js/route_detail.js, templates/routes/place_routes.html
=> refactor: 호버 삭제 및 alert js 수정

apps/routes/views.py, templates/users/routes.html
=> fix: 마이페이지에서 루트 삭제 시 url 수정

static/js/script.js
=> fix: 루트에 추가 2번 되는거 수정

static/js/script.js
=> [fix] like.js bugs

apps/users/adapter.py, requirements.txt, static/js/map.js, static/js/tabbar.js
=> fix: 대분류 선택시 지도 버그 해결

static/css/main.css
-   [x] 리뷰 반영 (Review Update)
-   작업 내용
-   [ ] Task1
=> [style] 루트 버튼 스타일 제작

templates/places/main.html, templates/search.html, templates/users/mypage.html
=> fix: 지도 api 비동기화

apps/users/forms.py, apps/users/urls.py, apps/users/views.py, templates/account/password_reset.html
-   [x] 기능 추가 (Feature)
-   작업 내용
-   [ ] Task1
=> feat: 소셜로그인 비밀번호 초기화 block

templates/search.html
=> fix: search.html 버그 수정

apps/places/urls.py
=> fix: main 변경

static/css/account/login.css, static/css/account/signup.css, static/css/search.css, templates/account/login.html, templates/account/signup.html, templates/search.html
=> fix: 로그아웃 시 검색결과 레이아웃

apps/reviews/models.py
=> fix: reviews의 model 수정
